name: System
version: '${project.version}'
main: de.webcode.system.ServerSystem
api-version: 1.19
authors: [ TheWebcode ]
description: Server System
commands:
  warn:
  warns:
  gm:
    aliases:
      - gmc
      - gms
      - gma
      - gmspec
  skick:
  tc:
    aliases:
      - teamchat
  bc:
    aliases:
      - broadcast
  chatsel:
    aliases:
      - chatselection
  clearchat:
    aliases:
      - cc
